export const recipes = [
  {
    nombre: "Chips de Kale",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 15 min", "Menos de 1€", "Vegana", "Sin Gluten"],
    calorias: 88.1,
    p: 6.5,
    c: 6.3,
    f: 4.1,
    ingredientes: [
      { n: "Kale", q: 300, u: "g" },
      { n: "AOVE", q: 5, u: "ml" },
      { n: "Especias", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Precalienta el horno a 200 grados (arriba y abajo). 2. Corta el kale en trozos de unos 4 cm. 3. Ponlos en un bol y mezcla con AOVE. 4. En una bandeja cubierta con papel de hornear, dispón los trozos de kale sin amontonar. 5. Hornea unos 10 minutos, vigilando que no se quemen. 6. Deja enfriar y añade sal y las especias que te gusten.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Guacamole con Palitos de Zanahoria",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 10 min", "Menos de 1€", "Vegana", "Sin Gluten"],
    calorias: 244.3,
    p: 3.22,
    c: 10.02,
    f: 21.26,
    ingredientes: [
      { n: "Zanahorias", q: 2, u: "unidades" },
      { n: "Aguacates", q: 2, u: "unidades" },
      { n: "Cebolleta", q: 0.5, u: "unidad" },
      { n: "Tomate", q: 1, u: "unidad" },
      { n: "Zumo de limón", q: 10, u: "ml" },
      { n: "Cilantro fresco", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Lava la zanahoria, pélala y córtala en bastones. 2. Pica la cebolla y el cilantro. 3. Corta el tomate en dados. 4. Extrae la pulpa del aguacate, machácala y riégala con el zumo de limón. 5. Mezcla el aguacate con el tomate, la cebolla y el cilantro. Sazona y sirve.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Zanahorias Encurtidas 'Para Mañana'",
    tipo: "Snacks y Entrantes",
    tags: ["Vegana", "Sin Gluten"],
    calorias: 131.51,
    p: 1.15,
    c: 9.07,
    f: 10.07,
    ingredientes: [
      { n: "Zanahorias", q: 2, u: "unidades" },
      { n: "Hierbabuena o Menta", q: 10, u: "g" },
      { n: "Perejil fresco", q: 10, u: "g" },
      { n: "Ajo", q: 5, u: "g" },
      { n: "AOVE", q: 20, u: "ml" },
      { n: "Vinagre", q: 30, u: "ml" },
      { n: "Pimienta negra", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Corta las zanahorias en tiras finas. 2. Pica el ajo, mézclalo con sal y pimienta y deja reposar 15 minutos. 3. Pica las hierbas y añádelas a la zanahoria junto con el ajo. 4. Mezcla el AOVE y el vinagre y añádelo a las zanahorias. 5. Deja reposar 24 horas antes de consumir.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Hummus de Remolacha con Crudités",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 15 min", "Vegetariana", "Sin Gluten"],
    calorias: 461.97,
    p: 14.77,
    c: 33.38,
    f: 29.93,
    ingredientes: [
      { n: "Remolacha cocida y pelada", q: 1, u: "unidad" },
      { n: "Garbanzos cocidos", q: 1, u: "bote" },
      { n: "Yogurt natural", q: 1, u: "cucharada" },
      { n: "Diente de ajo", q: 1, u: "unidad" },
      { n: "Apio", q: 40, u: "g" },
      { n: "Pimiento rojo", q: 40, u: "g" },
      { n: "Zumo de limón", q: 10, u: "ml" },
      { n: "Tahini", q: 1, u: "cucharada" },
      { n: "AOVE", q: 40, u: "ml" },
      { n: "Comino tostado y molido", q: 5, u: "g" },
      { n: "Pimentón", q: 5, u: "g" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Bate la remolacha, los garbanzos, el yogur, el tahini, el ajo, el AOVE, el comino, la sal y el zumo de limón. 2. Si te gusta más ligero, añade un poco de agua y vuelve a batir. 3. Espolvorea con pimentón y sirve con bastones de pimiento rojo y apio.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Patatitas Dos Salsas",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 10 min", "Menos de 1€", "Vegetariana", "Sin Gluten"],
    calorias: 336.08,
    p: 10.86,
    c: 41.12,
    f: 14.24,
    ingredientes: [
      { n: "Patatas baby", q: 400, u: "g" },
      { n: "Yogures griegos", q: 2, u: "unidades" },
      { n: "Hojas de hierbabuena", q: null, u: "al gusto" },
      { n: "Diente de ajo", q: 0.5, u: "unidad" },
      { n: "Zumo de limón", q: null, u: "al gusto" },
      { n: "Curry", q: 1, u: "cucharadita" },
      { n: "Pimienta negra", q: null, u: "al gusto" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Cuece las patatas en el microondas. 2. Para la primera salsa, mezcla un yogur con hierbabuena picada, medio ajo, AOVE, zumo de limón y sal. 3. Para la segunda salsa, mezcla el otro yogur con curry, pimienta y AOVE. 4. Sirve las patatas con las salsas.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Falso Sushi de Pepino, Yogur y Queso Feta",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 15 min", "Menos de 1€", "Vegetariana", "Sin Gluten"],
    calorias: 185.78,
    p: 8.29,
    c: 10.66,
    f: 12.22,
    ingredientes: [
      { n: "Pepino holandés", q: 1, u: "unidad" },
      { n: "Pimiento amarillo", q: 0.5, u: "unidad" },
      { n: "Yogur griego natural", q: 1, u: "unidad" },
      { n: "Cebolla morada", q: 0.5, u: "unidad" },
      { n: "Diente de ajo", q: 0.5, u: "unidad" },
      { n: "Queso feta", q: 50, u: "g" },
      { n: "Ralladura de limón", q: 3, u: "g" },
      { n: "Pimienta molida", q: null, u: "al gusto" },
      { n: "AOVE", q: 10, u: "ml" },
    ],
    preparacion:
      "1. Corta tiras finas de pepino y sécalas bien. 2. Corta el pimiento y la cebolla en cuadraditos pequeños. 3. Prepara una crema con el yogur, el queso feta, el ajo picado, la ralladura de limón, pimienta y AOVE. 4. Sobre cada tira de pepino pon una cucharada de crema, el pimiento y la cebolla, y enróllalo. 5. Sirve frío.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Gazpacho de Sandía y Feta",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 10 min", "Menos de 2€", "Vegetariana", "Sin Gluten"],
    calorias: 310.4,
    p: 8.39,
    c: 22.14,
    f: 20.92,
    ingredientes: [
      { n: "Tomates pera", q: 3, u: "unidades" },
      { n: "Sandía", q: 1, u: "trozo" },
      { n: "Cebolleta", q: 0.5, u: "unidad" },
      { n: "Diente de ajo", q: 1, u: "unidad" },
      { n: "Pimiento rojo", q: 0.5, u: "unidad" },
      { n: "Queso feta", q: 50, u: "g" },
      { n: "Hojas de albahaca escaldada", q: null, u: "al gusto" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Vinagre", q: null, u: "al gusto" },
      { n: "Pimienta", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. En una batidora, pon los tomates, la sandía sin piel ni pepitas, la cebolleta, el pimiento y la albahaca. 2. Añade 3-4 cucharadas de aceite, dos de vinagre y sal. 3. Bate todo hasta lograr una textura fina. 4. Sirve acompañado de trozos de sandía y queso feta.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Ensalada de Frutos Rojos, Setas y Cuscús",
    tipo: "Platos Completos",
    tags: ["Menos de 10 min", "Menos de 2€", "Vegetariana"],
    calorias: 387.62,
    p: 16.54,
    c: 31.27,
    f: 21.82,
    ingredientes: [
      { n: "Queso rulo de cabra", q: 100, u: "g" },
      { n: "Brotes de lechuga", q: 150, u: "g" },
      { n: "Cuscús integral", q: 50, u: "g" },
      { n: "Setas ostra", q: 200, u: "g" },
      { n: "Frutos rojos", q: 200, u: "g" },
      { n: "Cebollino", q: null, u: "al gusto" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Diente de ajo", q: 0.5, u: "unidad" },
      { n: "Vinagre", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Hidrata el cuscús según las indicaciones del fabricante. 2. Limpia y corta las setas en tiras y saltéalas con ajo, AOVE y sal. 3. Tuesta las rodajas de queso de cabra en la sartén. 4. Monta el plato con una base de ensalada, y dispón encima el rulo de cabra y los frutos rojos. 5. Acompaña con el cuscús y aliña con AOVE y vinagre. Espolvorea con cebollino.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Helado Casero de Yogur, Chocolate y Plátano",
    tipo: "Postres",
    tags: ["Menos de 10 min", "Menos de 1€", "Vegetariana", "Sin Gluten"],
    calorias: 121.59,
    p: 3.34,
    c: 17.9,
    f: 4.07,
    ingredientes: [
      { n: "Yogur natural", q: 1, u: "unidad" },
      { n: "Plátano sin piel", q: 1, u: "unidad" },
      { n: "Cacao puro", q: 1, u: "cucharada" },
    ],
    preparacion:
      "1. Machaca el plátano con un tenedor. 2. Mézclalo con el yogur y el cacao. 3. Coloca la mezcla en moldes. 4. Pincha las paletas y ponlo en el congelador.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Pudding de Chía con Mango",
    tipo: "Postres",
    tags: ["Menos de 15 min", "Menos de 2€", "Vegana", "Sin Gluten"],
    calorias: 277.76,
    p: 8.61,
    c: 30.18,
    f: 44.47,
    ingredientes: [
      { n: "Mango duro", q: 0.5, u: "unidad" },
      { n: "Semillas de chía", q: 50, u: "g" },
      { n: "Leche de coco", q: 400, u: "ml" },
    ],
    preparacion:
      "1. Mezcla la chía con la leche de coco y deja que se hidrate (idealmente, desde la noche anterior). 2. Pela el mango y córtalo en trozos pequeños, reservando un cuarto en daditos para decorar. 3. Tritura el resto del mango hasta hacer un puré. 4. Monta el vaso alternando capas de puré de mango y de chía con coco. 5. Decora con los daditos de mango.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Carpaccio de Remolacha y Champiñón",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 10 min", "Menos de 2€", "Vegetariana", "Sin Gluten"],
    calorias: 361.92,
    p: 11.04,
    c: 13.83,
    f: 29.16,
    ingredientes: [
      { n: "Remolacha cocida y pelada", q: 1, u: "unidad" },
      { n: "Champiñones", q: 10, u: "unidades" },
      { n: "Queso manchego curado", q: 30, u: "g" },
      { n: "Avellanas", q: 10, u: "unidades" },
      { n: "Rúcula", q: 100, u: "g" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Vinagre", q: null, u: "al gusto" },
      { n: "Pimienta", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Corta la remolacha y los champiñones en láminas muy finas. 2. Dispón la remolacha en la base de un plato y coloca los champiñones encima. 3. Pon un puñado de rúcula en el centro y añade unas lascas de queso. 4. Prepara un aliño mezclando AOVE, vinagre, las avellanas picadas y sal. 5. Vierte el aliño sobre el carpaccio.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Dip de Guisantes con Hierbabuena y Totopos Caseros",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 15 min", "Menos de 2€", "Vegetariana"],
    calorias: 366,
    p: 19.65,
    c: 21.45,
    f: 22.4,
    ingredientes: [
      { n: "Guisantes congelados", q: 300, u: "g" },
      { n: "Queso fresco", q: 250, u: "g" },
      { n: "Pistachos", q: 15, u: "g" },
      { n: "Tortillas de trigo integral", q: 2, u: "unidades" },
      { n: "Diente de ajo", q: 0.5, u: "unidad" },
      { n: "Hojas de hierbabuena", q: null, u: "al gusto" },
      { n: "AOVE", q: 10, u: "ml" },
      { n: "Pimentón", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Para los totopos, corta cada tortilla en 8 triángulos, píntalos con AOVE, añade sal y hornea a 180°C por 10 minutos. 2. Cocina los guisantes en el microondas por 4 minutos, tritúralos con un tenedor y deja enfriar. 3. Mezcla el queso con el ajo, pistachos, hierbabuena, AOVE, sal y pimienta. 4. Incorpora el puré de guisantes a la mezcla de queso. 5. Sirve el dip con los totopos espolvoreados con pimentón.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Escarola con Granada",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 8 min", "Menos de 1€", "Vegana", "Sin Gluten"],
    calorias: 181.99,
    p: 4.63,
    c: 24.51,
    f: 7.27,
    ingredientes: [
      { n: "Escarola", q: 300, u: "g" },
      { n: "Granada", q: 1, u: "unidad" },
      { n: "Diente de ajo", q: 1, u: "unidad" },
      { n: "Comino en grano", q: null, u: "al gusto" },
      { n: "AOVE", q: 10, u: "ml" },
      { n: "Vinagre", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Lava, escurre y trocea la escarola. 2. Desgrana la granada. 3. Tuesta los granos de comino y tritúralos en un mortero con el ajo, sal, vinagre y AOVE. 4. Vuelca el aliño sobre la escarola, incorpora la granada, mezcla y sirve.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Tosta de Aguacate con Requesón",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 5 min", "Menos de 2€", "Vegetariana"],
    calorias: 350.61,
    p: 11.52,
    c: 30.3,
    f: 20.37,
    ingredientes: [
      { n: "Aguacate", q: 1, u: "unidad" },
      { n: "Tarrina de requesón", q: 1, u: "unidad" },
      { n: "Tomates cherry", q: 80, u: "g" },
      { n: "Rebanadas de pan integral", q: 2, u: "unidades" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Tuesta el pan. 2. Extiende el requesón sobre las tostadas. 3. Corta el aguacate y el tomate y colócalos sobre el requesón. 4. Añade sal y un chorrito de AOVE.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Barquitas de Berenjena con Yogur y Manzana",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 15 min", "Menos de 2€", "Vegetariana", "Sin Gluten"],
    calorias: 191.88,
    p: 6.02,
    c: 25.66,
    f: 7.24,
    ingredientes: [
      { n: "Berenjena", q: 1, u: "unidad" },
      { n: "Yogur natural", q: 1, u: "unidad" },
      { n: "Cebolla roja", q: 1, u: "unidad" },
      { n: "Manzana verde ácida", q: 1, u: "unidad" },
      { n: "Zumo de limón", q: 80, u: "ml" },
      { n: "Diente de ajo", q: 1, u: "unidad" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Pimienta", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Corta la berenjena por la mitad y ásala en el microondas tapada por 10 minutos. Deja templar y extrae la carne, reservando la piel. 2. Pica la cebolla y macérala en zumo de limón. 3. Pica el ajo y media manzana y mézclalo con la carne de la berenjena, el yogur y la cebolla marinada. 4. Rellena la piel de la berenjena con la mezcla, salpimenta y decora con la otra media manzana en trozos.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Escabeche de Sardinas",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 15 min", "Menos de 2€", "Sin Gluten"],
    calorias: 542.33,
    p: 30.59,
    c: 4.08,
    f: 44.85,
    ingredientes: [
      { n: "Sardinas limpias", q: 500, u: "g" },
      { n: "Diente de ajo", q: 1, u: "unidad" },
      { n: "Vinagre", q: 30, u: "ml" },
      { n: "Pimentón", q: 6, u: "g" },
      { n: "Granos de pimienta negra", q: null, u: "al gusto" },
      { n: "Hoja de laurel", q: 1, u: "unidad" },
      { n: "AOVE", q: 60, u: "ml" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. En una sartén con un poco de AOVE, dora el ajo aplastado y con piel. 2. Añade el pimentón, el resto del aceite y el vinagre, y cuece 5 minutos. 3. Añade el laurel, los granos de pimienta y las sardinas y cuece 10 minutos más. 4. Deja enfriar y consume al día siguiente.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Crema de Calabaza y Queso Azul",
    tipo: "Snacks y Entrantes",
    tags: ["Menos de 15 min", "Menos de 2€", "Vegetariana", "Sin Gluten"],
    calorias: 375.74,
    p: 14.04,
    c: 12.62,
    f: 29.9,
    ingredientes: [
      { n: "Calabaza cacahuete", q: 500, u: "g" },
      { n: "Queso azul", q: 80, u: "g" },
      { n: "Puerro", q: 80, u: "g" },
      { n: "Agua o caldo de verduras", q: 250, u: "ml" },
      { n: "Semillas de calabaza", q: 10, u: "g" },
      { n: "Pimentón", q: 10, u: "g" },
      { n: "AOVE", q: 30, u: "ml" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Pela y corta la calabaza en dados. Corta el puerro en rodajas. 2. Calienta aceite en una olla y saltea el puerro. 3. Añade los dados de calabaza, el agua o caldo y sal. Cuece por 10 minutos. 4. Separa del fuego, añade el pimentón y remueve. 5. Tritura la crema con una batidora. 6. Sirve la crema sobre unos dados de queso azul en un plato hondo y añade las semillas de calabaza.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Alubia Confetti",
    tipo: "Platos Completos",
    tags: ["Menos de 5 min", "Menos de 1€", "Vegana", "Sin Gluten"],
    calorias: 403.95,
    p: 18.15,
    c: 59.82,
    f: 10.23,
    ingredientes: [
      { n: "Bote de alubias rojas", q: 1, u: "unidad" },
      { n: "Arroz integral precocido", q: 1, u: "tarrina" },
      { n: "Lata pequeña de maíz", q: 1, u: "unidad" },
      { n: "Pimiento rojo", q: 0.5, u: "unidad" },
      { n: "La parte verde de 2 cebolletas", q: null, u: "al gusto" },
      { n: "Zumo de limón", q: 20, u: "ml" },
      { n: "AOVE", q: 20, u: "ml" },
      { n: "Cilantro fresco", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Cocina el arroz en el microondas y deja enfriar. 2. Corta los tallos de cebolleta en aros y macéralos con zumo de limón. 3. En un bol, mezcla las alubias y el maíz escurridos, el pimiento en dados, el arroz y la cebolleta con su limón. 4. Aliña con AOVE y sal, y remata con cilantro picado.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Salmón Exprés al Microondas",
    tipo: "Platos Completos",
    tags: ["Menos de 10 min", "Menos de 3€"],
    calorias: 561.81,
    p: 64.9, // La tabla tiene un error, probablemente sea 44.9
    c: 24.25,
    f: 31.69,
    ingredientes: [
      { n: "Lomo de salmón", q: 1, u: "unidad" },
      { n: "Arroz basmati precocido", q: 1, u: "vasito" },
      { n: "Pepino", q: 1, u: "unidad" },
      { n: "Cebolleta", q: 0.5, u: "unidad" },
      { n: "Jengibre rallado", q: null, u: "al gusto" },
      { n: "Salsa de soja", q: 1, u: "cucharada" },
      { n: "Vinagre", q: 1, u: "cucharada" },
      { n: "Semillas de sésamo", q: null, u: "al gusto" },
      { n: "Eneldo seco", q: null, u: "al gusto" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Cocina el arroz en el microondas. 2. Pon el salmón en un plato untado con AOVE, sazona con sal y eneldo, cúbrelo y cocínalo en el microondas por 5 minutos. 3. Corta el pepino en tiras y la cebolla. 4. Prepara una ensalada con el pepino y la cebolla escurridos. 5. Mezcla la soja, el vinagre, el sésamo y el jengibre para el aliño. 6. Sirve el salmón con la ensalada aliñada.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Tallarines de Calabacín y Zanahoria con Vinagreta de Nueces",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 1€", "Vegana"],
    calorias: 222.14,
    p: 4.76,
    c: 10.77,
    f: 17.78,
    ingredientes: [
      { n: "Zanahorias", q: 2, u: "unidades" },
      { n: "Calabacín", q: 1, u: "unidad" },
      { n: "Diente de ajo", q: 1, u: "unidad" },
      { n: "Nueces", q: 3, u: "unidades" },
      { n: "Semillas de sésamo", q: 0.5, u: "cucharada" },
      { n: "Mostaza de Dijon", q: 3, u: "g" },
      { n: "AOVE", q: 20, u: "ml" },
      { n: "Vinagre", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Con un espiralizador, forma tallarines con el calabacín y la zanahoria. 2. Saltéalos a fuego fuerte en una sartén con AOVE y ajo picado. 3. Prepara una vinagreta con AOVE, vinagre y mostaza. 4. Pica las nueces. 5. Mezcla los tallarines con la vinagreta y, al servir, espolvorea con las nueces y el sésamo.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Brocheta de Pollo Especiado",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 2€"],
    calorias: 316.08,
    p: 38.69,
    c: 12.34,
    f: 12.44,
    ingredientes: [
      { n: "Pechuga de pollo", q: 0.5, u: "unidad" },
      { n: "Cebolla", q: 0.5, u: "unidad" },
      { n: "Tomates cherry", q: 60, u: "g" },
      { n: "Nectarina", q: 1, u: "unidad" },
      { n: "Pimiento verde", q: 1, u: "unidad" },
      { n: "Rúcula", q: 100, u: "g" },
      { n: "Nueces", q: 3, u: "unidades" },
      { n: "Pimentón", q: 8, u: "g" },
      { n: "Zumo de limón", q: null, u: "al gusto" },
      { n: "AOVE", q: 10, u: "ml" },
      { n: "Pimienta molida", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Corta el pollo en dados y déjalo marinar con cebolla rallada, pimentón, zumo de limón, AOVE y sal. 2. Corta el pimiento, la nectarina y la cebolla en trozos. 3. Forma las brochetas alternando pollo, fruta y verduras. 4. Cocínalas a la plancha. 5. Sirve con una ensalada de rúcula y nueces.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Miniburger de Alubias y Atún",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 2€"],
    calorias: 402.38,
    p: 38.61,
    c: 24.59,
    f: 16.62,
    ingredientes: [
      { n: "Bote pequeño de alubias blancas cocidas", q: 1, u: "unidad" },
      { n: "Lata de atún en aceite de oliva o al natural", q: 1, u: "unidad" },
      { n: "Huevo", q: 1, u: "unidad" },
      { n: "Pan rallado", q: 30, u: "g" },
      { n: "Lechuga, espinacas u otras hojas verdes", q: 200, u: "g" },
      { n: "Mostaza de Dijon", q: null, u: "al gusto" },
      { n: "Limón", q: 1, u: "unidad" },
      { n: "Tomates cherry", q: null, u: "al gusto" },
      { n: "Orégano seco", q: null, u: "al gusto" },
      { n: "AOVE", q: 5, u: "ml" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Escurre y aplasta las alubias hasta formar una pasta. 2. Incorpora el atún escurrido, un huevo y pan rallado. 3. Aliña con mostaza, orégano, la ralladura de un limón y sal y forma un puré. 4. Con la masa, forma las minibúrguers y cocínalas en una sartén hasta que estén doradas. 5. Sirve con las hojas verdes y tomates aliñados.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Poke de Pollo al Estilo Harvard",
    tipo: "Platos Completos",
    tags: ["Menos de 10 min", "Menos de 2€", "Sin Gluten"],
    calorias: 450.76,
    p: 40.27,
    c: 38.76,
    f: 14.96,
    ingredientes: [
      { n: "Pechuga de pollo", q: 0.5, u: "unidad" },
      { n: "Arroz integral precocido", q: 1, u: "vasito" },
      { n: "Melocotón", q: 1, u: "unidad" },
      { n: "Trozo de melón", q: 1, u: "unidad" },
      { n: "Canónigos", q: 80, u: "g" },
      { n: "Tomate cherry", q: 100, u: "g" },
      { n: "Pepino", q: 100, u: "g" },
      { n: "Anacardos", q: 10, u: "unidades" },
      { n: "Zumo de limón", q: null, u: "al gusto" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Corta el pollo en trozos y saltéalo en una sartén. 2. Cuece el arroz en el microondas. 3. Pela y lamina el melocotón, el melón, el tomate y el pepino. 4. Monta el poke en un bol, combinando todos los ingredientes. 5. Añade los anacardos y aliña con AOVE, zumo de limón y sal.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Rainbow Wrap con Salsa de Anchoas",
    tipo: "Platos Completos",
    tags: ["Menos de 10 min", "Menos de 2€"],
    calorias: 274.17,
    p: 15.53,
    c: 13.84,
    f: 17.41,
    ingredientes: [
      { n: "Tortillas de trigo integral", q: 2, u: "unidades" },
      { n: "Hojas de espinacas", q: 150, u: "g" },
      { n: "Queso fresco", q: 60, u: "g" },
      { n: "Cebolla morada", q: 0.5, u: "unidad" },
      { n: "Zanahoria", q: 1, u: "unidad" },
      { n: "Pimiento rojo", q: 0.5, u: "unidad" },
      { n: "Huevos", q: 2, u: "unidades" },
      { n: "Filetes de anchoa en conserva", q: 4, u: "unidades" },
      { n: "Diente de ajo", q: 0.5, u: "unidad" },
      { n: "Zumo de limón", q: null, u: "al gusto" },
      { n: "AOVE", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Cuece los huevos por 5 minutos y pélalos. 2. Para la salsa, bate los huevos cocidos con el ajo, las anchoas, aceite y zumo de limón. 3. Corta en tiras la cebolla, el pimiento y la zanahoria. Corta el queso en láminas. 4. Calienta la tortilla, úntala con la salsa y dispón encima las verduras y el queso. 5. Enróllala y sirve.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Mini Green Pizza",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 2€", "Vegetariana"],
    calorias: 408.48,
    p: 17.48,
    c: 5.53,
    f: 35.16,
    ingredientes: [
      { n: "Pitas integrales", q: 2, u: "unidades" },
      { n: "Brócoli", q: 150, u: "g" },
      { n: "Mozzarella fresca", q: 100, u: "g" },
      { n: "Rúcula", q: 100, u: "g" },
      { n: "Nueces peladas crudas", q: 25, u: "g" },
      { n: "Queso parmesano", q: 30, u: "g" },
      { n: "Ajo", q: 0.5, u: "unidad" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Pimienta", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Prepara un pesto batiendo la rúcula, el ajo, el parmesano, las nueces, aceite y sal. 2. Cocina el brócoli en ramilletes pequeños en el microondas por 4 minutos. 3. Corta las pitas transversalmente. 4. En cada media pita, coloca una rodaja de mozzarella, unos ramilletes de brócoli y cubre con el pesto. 5. Gratina en el horno por 3 minutos o hasta que se funda el queso.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Lubina con Patatas y Cama de Verduras",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 2€", "Sin Gluten"],
    calorias: 388.86,
    p: 45.94,
    c: 20.0,
    f: 13.9,
    ingredientes: [
      { n: "Lomos de lubina sin piel ni espinas", q: 2, u: "unidades" },
      { n: "Patatas medianas", q: 2, u: "unidades" },
      { n: "Cebolla", q: 0.5, u: "unidad" },
      { n: "Tomate", q: 1, u: "unidad" },
      { n: "Pimientos de colores", q: 150, u: "g" },
      { n: "AOVE", q: 10, u: "ml" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Cuece la patata en el microondas por 8 minutos. 2. Cocina la cebolla en aros en el microondas por 5 minutos. 3. Añade el tomate y los pimientos a la cebolla y cocina 5 minutos más. 4. Coloca el pescado sobre las verduras, añade sal, AOVE, tapa y cocina 5 minutos a media potencia. 5. Sirve la lubina con las verduras y las patatas cocidas en rodajas.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Espaguetis del Estudiante",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 2€"],
    calorias: 515.62,
    p: 23.19,
    c: 61.84,
    f: 19.5,
    ingredientes: [
      { n: "Espaguetis integrales", q: 160, u: "g" },
      { n: "Lata de tomate natural triturado", q: 1, u: "unidad" },
      { n: "Lata de sardinas en conserva", q: 1, u: "unidad" },
      { n: "Dientes de ajo", q: 2, u: "unidades" },
      { n: "Aceitunas negras", q: 25, u: "g" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Orégano seco", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Cuece la pasta. 2. Mientras, prepara la salsa: calienta AOVE con los ajos en el microondas por 1 minuto, añade el tomate, orégano y cocina 10 minutos más. 3. Mezcla la pasta con la salsa, las sardinas escurridas y desmenuzadas y las aceitunas en rodajas. 4. Sirve espolvoreando con orégano.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Tortilla de Patata y Calabacín al Microondas",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 1€", "Vegetariana", "Sin Gluten"],
    calorias: 229.34,
    p: 4.38,
    c: 26.9,
    f: 11.58,
    ingredientes: [
      { n: "Patatas medianas", q: 2, u: "unidades" },
      { n: "Cebolla", q: 0.5, u: "unidad" },
      { n: "Calabacín pequeño", q: 1, u: "unidad" },
      { n: "Huevos", q: 4, u: "unidades" },
      { n: "AOVE", q: 22, u: "ml" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Cocina la cebolla en el microondas por 5 min. 2. Añade la patata en láminas y cocina 6 min más. 3. Incorpora el calabacín en rodajas y cocina otros 4 min. 4. Bate los huevos con sal, incorpora las verduras cocinadas y cuaja la tortilla en una sartén con AOVE.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Pitas con Huevo, Espinacas y Queso",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 2€", "Vegetariana"],
    calorias: 302.68,
    p: 17.33,
    c: 5.51,
    f: 23.48,
    ingredientes: [
      { n: "Huevos", q: 3, u: "unidades" },
      { n: "Espinacas crudas", q: 150, u: "g" },
      { n: "Tomates secos", q: 5, u: "unidades" },
      { n: "Pitas integrales", q: 2, u: "unidades" },
      { n: "Mini rulo de cabra", q: 1, u: "unidad" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Pimienta", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Hidrata los tomates secos en agua caliente. 2. Bate los huevos y cuájalos en una sartén (revueltos). 3. Calienta las pitas. 4. Rellena las pitas con los huevos revueltos, las espinacas, el queso de cabra y los tomates hidratados y picados.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Alcachofas con Langostinos",
    tipo: "Platos Completos",
    tags: ["Menos de 10 min", "Menos de 2€", "Sin Gluten"],
    calorias: 242.59,
    p: 31.5,
    c: 13.15,
    f: 7.11,
    ingredientes: [
      { n: "Langostinos congelados", q: 250, u: "g" },
      { n: "Corazones de alcachofa congelados", q: 250, u: "g" },
      { n: "Cebolla", q: 1, u: "unidad" },
      { n: "Diente de ajo", q: 1, u: "unidad" },
      { n: "AOVE", q: 10, u: "ml" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Descongela y pela los langostinos. 2. Cocina los corazones de alcachofa en el microondas por 5 minutos. 3. Sofríe la cebolla y el ajo picado en una sartén. 4. Cuando la cebolla esté transparente, añade las alcachofas cocidas y los langostinos pelados. Saltea y sirve caliente.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Lentejas con Arroz y Cúrcuma",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 1€", "Vegana", "Sin Gluten"],
    calorias: 593,
    p: 24.67,
    c: 82.54,
    f: 18.24,
    ingredientes: [
      { n: "Bote de lentejas cocidas", q: 1, u: "unidad" },
      { n: "Vasito de arroz integral precocido", q: 1, u: "unidad" },
      { n: "Cebolla", q: 1, u: "unidad" },
      { n: "Zanahoria", q: 1, u: "unidad" },
      { n: "Tomate maduro", q: 1, u: "unidad" },
      { n: "Cúrcuma", q: null, u: "al gusto" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Pica la cebolla, el tomate y ralla la zanahoria. 2. Sofríe la cebolla, luego añade la zanahoria y el tomate. 3. Cuando el sofrito esté listo, añade las lentejas escurridas, cubre con agua y hierve 5 minutos. 4. Añade una cucharada de cúrcuma y tritura todo hasta hacer una crema. 5. Cocina el arroz en el microondas. 6. Sirve la crema en cuencos con el arroz cocido.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Garbanzos con Pisto y Ras el Hanout",
    tipo: "Platos Completos",
    tags: ["Menos de 10 min", "Menos de 2€", "Vegana", "Sin Gluten"],
    calorias: 297.95,
    p: 18.68,
    c: 41.88,
    f: 6.19,
    ingredientes: [
      { n: "Bote de garbanzos cocidos", q: 1, u: "unidad" },
      { n: "Bote de pisto en conserva", q: 1, u: "unidad" },
      { n: "Ras el hanout", q: 1, u: "cucharada" },
      { n: "Hojas de cilantro o hierbabuena", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Pon los garbanzos escurridos en una cazuela cubiertos de agua. 2. Añade el pisto y cuece unos minutos desde que empiece a hervir. 3. Incorpora una cucharada de ras el hanout y deja que vuelva a hervir. 4. Sirve caliente espolvoreado con cilantro o hierbabuena.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Escalivada con Alma de Germinados y Bacalao",
    tipo: "Platos Completos",
    tags: ["Menos de 10 min", "Menos de 2€", "Sin Gluten"],
    calorias: 395.86,
    p: 61.67,
    c: 9.08,
    f: 12.54,
    ingredientes: [
      { n: "Bote de escalivada en conserva", q: 1, u: "unidad" },
      { n: "Bacalao desalado y desmigado", q: 250, u: "g" },
      { n: "Germinados", q: 15, u: "g" },
      { n: "Cebolla morada", q: 1, u: "unidad" },
      { n: "Huevos", q: 2, u: "unidades" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Vinagre", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Cuece los huevos por 10 minutos, enfríalos y rállalos. 2. Escurre las verduras de la escalivada y móntalas en un plato. 3. Escurre las migas de bacalao y colócalas sobre las verduras. 4. Reparte la cebolleta cortada sobre el bacalao, añade el huevo rallado y remata con los germinados. 5. Aliña con AOVE, vinagre y sal.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Copazo de Ensaladilla",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 1€", "Sin Gluten"],
    calorias: 247.28,
    p: 10.26,
    c: 28.25,
    f: 10.36,
    ingredientes: [
      { n: "Patatas medianas", q: 2, u: "unidades" },
      { n: "Huevos", q: 2, u: "unidades" },
      { n: "Zanahoria", q: 1, u: "unidad" },
      { n: "Lata de atún al natural", q: 1, u: "unidad" },
      { n: "AOVE", q: 20, u: "ml" },
      { n: "Zumo de limón", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Cuece los huevos por 10 minutos. 2. Cuece las patatas y la zanahoria en el microondas. 3. Pela y corta en dados las patatas y la zanahoria cocidas. Mézclalo todo con el atún escurrido. 4. Para la salsa, bate los huevos duros pelados con el AOVE, zumo de limón y sal hasta formar una crema. 5. Mezcla la salsa con la ensaladilla y sirve.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Tortilla de Setas y Espinacas",
    tipo: "Platos Completos",
    tags: ["Menos de 10 min", "Menos de 2€", "Vegetariana", "Sin Gluten"],
    calorias: 210.73,
    p: 7.22,
    c: 9.26,
    f: 16.09,
    ingredientes: [
      { n: "Espinacas congeladas", q: 250, u: "g" },
      { n: "Setas de temporada", q: 250, u: "g" },
      { n: "Huevos", q: 4, u: "unidades" },
      { n: "Diente de ajo", q: 1, u: "unidad" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Saltea las espinacas congeladas en una sartén. 2. En otra sartén, saltea las setas troceadas con un ajo laminado hasta que pierdan el agua. 3. Bate los huevos con sal, añade las espinacas y las setas, y cuaja la tortilla en una sartén.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Olleta de Arroz Integral",
    tipo: "Platos Completos",
    tags: ["Menos de 15 min", "Menos de 2€", "Vegana", "Sin Gluten"],
    calorias: 424.8,
    p: 10.5,
    c: 46.2,
    f: 22.0,
    ingredientes: [
      { n: "Arroz integral precocido", q: 0.5, u: "vaso" },
      { n: "Acelgas", q: 100, u: "g" },
      { n: "Alubias blancas cocidas", q: 100, u: "g" },
      { n: "Judías verdes", q: 60, u: "g" },
      { n: "Nabo", q: 60, u: "g" },
      { n: "Patata", q: 1, u: "unidad" },
      { n: "Agua", q: 500, u: "ml" },
      { n: "Azafrán", q: null, u: "al gusto" },
      { n: "Comino", q: null, u: "al gusto" },
      { n: "AOVE", q: null, u: "al gusto" },
      { n: "Sal", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Pon a cocer la patata en trozos en una olla con agua, sal, comino y azafrán. 2. Cuando hierva, añade las acelgas, nabos y judías verdes troceadas. 3. Añade las alubias cocidas y deja cocer 15 minutos. 4. Cuece el arroz en el microondas y añádelo a la olla. 5. Apaga el fuego, añade AOVE y sirve caliente.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Ramen Casero",
    tipo: "Platos Completos",
    tags: ["Menos de 10 min", "Menos de 3€"],
    calorias: 311.15,
    p: 18.42,
    c: 30.41,
    f: 12.87,
    ingredientes: [
      { n: "Caldo vegetal", q: 1, u: "litro" },
      { n: "Fideos de arroz integrales", q: 50, u: "g" },
      { n: "Huevos", q: 2, u: "unidades" },
      { n: "Zanahoria rallada", q: 80, u: "g" },
      { n: "Brotes de soja", q: 40, u: "g" },
      { n: "Tallos verdes de cebolleta", q: 20, u: "g" },
      { n: "Semillas de sésamo", q: 10, u: "g" },
      { n: "Lámina de alga nori", q: 1, u: "unidad" },
    ],
    preparacion:
      "1. Cuece los huevos por 6 minutos y enfríalos. 2. Cuece los fideos según las indicaciones y resérvalos en un bol. 3. Calienta el caldo y viértelo sobre los fideos. 4. Añade la zanahoria rallada, los brotes de soja, el tallo de la cebolleta cortado y el huevo cocido partido por la mitad. 5. Decora con alga nori y sésamo molido.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Batido de Plátano y Arándanos con Avena",
    tipo: "Postres",
    tags: ["Menos de 5 min", "Menos de 1€"],
    calorias: 232.6,
    p: 8.77,
    c: 34.08,
    f: 6.8,
    ingredientes: [
      { n: "Arándanos", q: 100, u: "g" },
      { n: "Plátano", q: 0.5, u: "unidad" },
      { n: "Avena molida", q: 60, u: "g" },
      { n: "Taza de leche o bebida vegetal", q: 1, u: "unidad" },
      { n: "Canela o nuez moscada", q: null, u: "al gusto" },
      { n: "Hielo picado", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. En el vaso de la batidora, pon los arándanos, el medio plátano, la avena y la leche o bebida vegetal, y bate. 2. Añade hielo picado al gusto y espolvorea con canela molida o nuez moscada.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Piña a la Plancha con Cardamomo",
    tipo: "Postres",
    tags: ["Menos de 15 min", "Menos de 2€", "Vegana", "Sin Gluten"],
    calorias: 131.68,
    p: 0.65,
    c: 31.46,
    f: 0.36,
    ingredientes: [
      { n: "Piña natural", q: 0.5, u: "unidad" },
      { n: "Vaina de cardamomo verde", q: 1, u: "unidad" },
      { n: "Piel de lima o limón", q: null, u: "al gusto" },
      { n: "Hojas de hierbabuena", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Pela la piña, retira el centro y córtala en cuñas. 2. Asa las cuñas en una sartén antiadherente hasta que estén doradas. 3. Muele el cardamomo. 4. Sirve la piña espolvoreada con el cardamomo, ralladura de lima o limón y hojas de hierbabuena.",
    source: "recipeSources.gobierno",
  },
  {
    nombre: "Gajos de Naranja con Menta y Chocolate",
    tipo: "Postres",
    tags: ["Menos de 15 min", "Menos de 2€", "Vegana", "Sin Gluten"],
    calorias: 318.09,
    p: 6.13,
    c: 27.2,
    f: 20.53,
    ingredientes: [
      { n: "Naranjas", q: 2, u: "unidades" },
      { n: "Chocolate negro (85%-90% cacao) para fundir", q: 100, u: "g" },
      { n: "Hojas de menta", q: null, u: "al gusto" },
    ],
    preparacion:
      "1. Funde el chocolate en el microondas. 2. Pela las naranjas, separa los gajos y sécalos. 3. Sumerge cada gajo hasta la mitad en el chocolate fundido. 4. Colócalos en un plato separados y déjalos enfriar en la nevera por unos 10-15 minutos. 5. Sirve acompañados con hojas de menta.",
    source: "recipeSources.gobierno",
  },
];
